accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"


urlpatterns = [
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("profile/<int:pk>/", views.ProfileView.as_view(), name="profile"),
    path("profile_update/", views.UpdateProfileView.as_view(), name="profile_update"),
    path("change_password/", views.ChangePassword.as_view(), name="change_password"),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('wkdrmfmt/', admin.site.urls),
    path('', include('post.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views


app_name = "post"


urlpatterns = [
    path("", views.posts, name="home"),
    path("write/", views.CreatePosts.as_view(), name="write"),
    path("politics/", views.posts_politics, name="politics"),
    path("economy/", views.posts_economy, name="economy"),
    path("it/", views.posts_it, name="it"),
    path("company/", views.posts_company, name="company"),
    path("science/", views.posts_science, name="science"),
    path("society/", views.posts_society, name="society"),
    path("book_review/", views.posts_bookreview, name="book_review"),
    path("<int:pk>/", views.PostDetail.as_view(), name="detail"),
    path("edit/<int:pk>/", views.post_edit, name="edit"),
    path("delete/<int:pk>", views.post_delete, name="delete"),
    path("search/", views.SearchView.as_view(), name="search"),
]

templates/partials/nav.html
<div class=" d-flex justify-content-around flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <a href="{% url 'post:home' %}" class="col" id="no-mobile">
    <h5 class="mr-md-auto font-weight-normal">무제</h5>
  </a>
  <nav id="no-mobile" class="col-7 my-md-0 mr-md-3">
    <a class="p-2 mr-2 text-dark" href="{% url 'post:home' %}">전체</a>
    <a class="p-2 mr-2 text-dark" href="{% url 'post:politics' %}">정치</a>
    <a class="p-2 mr-2 text-dark" href="{% url 'post:economy' %}">경제</a>
    <a class="p-2 mr-2 text-dark" href="{% url 'post:it' %}">IT</a>
    <a class="p-2 mr-2 text-dark" href="{% url 'post:company' %}">기업</a>
    <a class="p-2 mr-2 text-dark" href="{% url 'post:science' %}">과학</a>
    <a class="p-2 mr-2 text-dark" href="{% url 'post:society' %}">사회/문화</a>
    <a class="p-2 mr-2 text-dark" href="{% url 'post:book_review' %}">책 리뷰</a>
  </nav>
  
  {% if user.is_authenticated %}
  <nav id="no-mobile" class="col-3">
    <a class="btn btn-outline-primary mr-3" href="{% url 'post:write' %}">글쓰기</a>
    <a class="btn btn-outline-primary mr-3" href="{{user.get_absolute_url}}">프로필</a>
    <a class="btn btn-outline-primary" href="{% url 'accounts:logout' %}">로그아웃</a>
  </nav>
  {% else %}
  <nav id="no-mobile" class="col-3">
    <a class="btn btn-outline-primary mr-3" href="{% url 'accounts:login' %}">로그인</a>
    <a class="btn btn-outline-primary" href="{% url 'accounts:signup' %}">회원가입</a>
  </nav>
  {% endif %}

  <div id="mobile" class="text-left">
      <a href="{% url 'post:home' %}" style="font-size: 15px;">
        <h5 class="font-weight-normal">무제</h5>
      </a>
      <nav style="font-size: 10px;">
        <a class="text-dark" href="{% url 'post:home' %}">전체</a>
        <a class="text-dark" href="{% url 'post:politics' %}">정치</a>
        <a class="text-dark" href="{% url 'post:economy' %}">경제</a>
        <a class="text-dark" href="{% url 'post:it' %}">IT</a>
        <a class="text-dark" href="{% url 'post:company' %}">기업</a>
        <a class="text-dark" href="{% url 'post:science' %}">과학</a>
        <a class="text-dark" href="{% url 'post:society' %}">사회/문화</a>
        <a class="text-dark" href="{% url 'post:book_review' %}">책 리뷰</a>
      </nav>
  </div>
</div>

templates/partials/page_nav.html
<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if post_list.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{post_list.previous_page_number}}"
        >&laquo;</a
      >
    </li>
    {% endif %} {% for page in page_obj %}
    <li class="page-item">
      <a class="page-link" href="?page={{page}}">{{page}}</a>
    </li>
    {% endfor %} {% if post_list.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{post_list.next_page_number}}"
        >&raquo;</a
      >
    </li>
    {% endif %}
  </ul>
</nav>