accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"


urlpatterns = [
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("profile/<int:pk>/", views.ProfileView.as_view(), name="profile"),
    path("profile_update/", views.UpdateProfileView.as_view(), name="profile_update"),
    path("change_password/", views.ChangePassword.as_view(), name="change_password"),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('wkdrmfmt/', admin.site.urls),
    path('', include('post.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views


app_name = "post"


urlpatterns = [
    path("", views.posts, name="home"),
    path("write/", views.CreatePosts.as_view(), name="write"),
    path("politics/", views.posts_politics, name="politics"),
    path("economy/", views.posts_economy, name="economy"),
    path("it/", views.posts_it, name="it"),
    path("company/", views.posts_company, name="company"),
    path("science/", views.posts_science, name="science"),
    path("society/", views.posts_society, name="society"),
    path("book_review/", views.posts_bookreview, name="book_review"),
    path("<int:pk>/", views.PostDetail.as_view(), name="detail"),
    path("edit/<int:pk>/", views.post_edit, name="edit"),
    path("delete/<int:pk>", views.post_delete, name="delete"),
    path("search/", views.SearchView.as_view(), name="search"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.db import models


class User(AbstractUser):
    avatar = models.ImageField(
        upload_to="accounts/%Y/%m", default="accounts/base_user.png", verbose_name="프로필 사진"
    )
    nickname = models.CharField(unique=True, max_length=10, verbose_name="닉네임")
    bio = models.CharField(blank=True, max_length=255, verbose_name="자기소개")

    def get_absolute_url(self):
        return reverse("accounts:profile", kwargs={"pk": self.pk})

accounts/forms.py
from django import forms
from django.forms import widgets
from django.utils.translation import gettext_lazy as _
from . import models


class LoginForm(forms.Form):
    username = forms.CharField(label=_("아이디"))
    password = forms.CharField(widget=forms.PasswordInput, label=_("비밀번호"))

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(username=username)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("패스워드가 틀립니다."))
        except models.User.DoesNotExist:
            self.add_error("password", forms.ValidationError("아이디가 존재하지 않습니다."))


class SignupForm(forms.ModelForm):
    password = forms.CharField(
        label=_("비밀번호"), widget=forms.PasswordInput(attrs={"placeholder": "비밀번호"})
    )
    password1 = forms.CharField(
        label=_("비밀번호 확인"), widget=forms.PasswordInput(attrs={"placeholder": "비밀번호 확인"})
    )

    class Meta:
        model = models.User
        fields = ("username", "nickname", "avatar", "bio")
        widgets = {
            "bio": widgets.Textarea(),
        }
        labels = {
            "username": "아이디",
            "nickname": "닉네임",
            "avatar": "프로필 사진",
            "bio": "자기소개",
            "password": "비밀번호",
        }

    def clean_username(self):
        username = self.cleaned_data.get("username")
        try:
            models.User.objects.get(username=username)
            raise forms.ValidationError("해당 아이디는 이미 존재합니다.")
        except models.User.DoesNotExist:
            return username

    def clean_nickname(self):
        nickname = self.cleaned_data.get("nickname")
        try:
            models.User.objects.get(nickname=nickname)
            raise forms.ValidationError("해당 닉네임 이미 존재합니다.")
        except models.User.DoesNotExist:
            return nickname

    def clean_passwrord(self):
        password = self.cleaned_data.get("password")
        password1 = self.changed_data.get("password1")
        if password != password1:
            raise forms.ValidationError("패스워드가 일치하지 않습니다.")
        else:
            return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        password = self.cleaned_data.get("password")
        user.set_password(password)
        user.save()

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.decorators import login_required
from django.urls.base import reverse_lazy, reverse
from django.shortcuts import redirect
from django.views.generic import FormView, UpdateView, DetailView
from . import models, forms, mixins


class UserLoginView(mixins.LoggedOutOnlyView, FormView):
    template_name = "accounts/login.html"
    form_class = forms.LoginForm
    success_url = reverse_lazy("post:home")
    context_object_name = "forms"

    def form_valid(self, form):
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            messages.success(self.request, f"어서오세요. {username}님")
            login(self.request, user)
        return super().form_valid(form)


@login_required
def log_out(request):
    messages.info(request, "로그아웃하였습니다.")
    logout(request)
    return redirect(reverse("post:home"))


class SignupView(mixins.LoggedOutOnlyView, FormView):
    template_name = "accounts/signup.html"
    form_class = forms.SignupForm
    success_url = reverse_lazy("post:home")

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            messages.success(self.request, f"어서오세요. {username}님")
            login(self.request, user)
        return super().form_valid(form)


class ProfileView(DetailView):
    model = models.User
    template_name = "accounts/profile.html"
    context_object_name = "user_obj"


class UpdateProfileView(UpdateView):
    model = models.User
    template_name = "accounts/update_profile.html"
    context_object_name = "user_obj"
    fields = (
        "nickname",
        "avatar",
        "bio",
    )

    def get_object(self, queryset=None):
        return self.request.user


class ChangePassword(PasswordChangeView):
    template_name = "accounts/change_password.html"

templates/accounts/change_password.html
{% extends 'layout.html' %} {% load bootstrap4 %} {% block title %} 무제 |
패스워드 변경 {% endblock %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %} {% bootstrap_form form %} {% buttons %}
        <button type="submit" class="btn btn-primary">
          {{ submit_label|default:"변경 완료" }}
        </button>
        {% endbuttons %}
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/accounts/login.html
{% extends 'layout.html' %} 
{% load bootstrap4 %} 

{% block title %} 
무제 | 로그인 
{% endblock %} 

{% block content %}
<div class="container w-50">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %} 
        {% bootstrap_form form %} 
        {% buttons %}
        <button type="submit" class="btn btn-primary">
          {{ submit_label|default:"로그인" }}
        </button>
        {% endbuttons %}
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/accounts/profile.html
{% extends 'layout.html' %} 
{% load bootstrap4 %} 

{% block title %} 무제 | 프로필 {% endblock %} 

{% block content %}
<div class="container d-flex">
  <div class="card mr-5" style="width: 10rem">
    {% if user_obj == request.user %}
    <a class="btn btn-primary m-3 btn-sm" href="{% url 'accounts:profile_update' %}" role="button">프로필 수정</a>
    {% endif %}
    <div class="d-flex justify-content-center mt-2">
      <img src="{{user_obj.avatar.url}}" style="height: 90px; width: 100px; background-size: cover" />
    </div>
    <p class="text-center">{{user_obj.nickname}}</p>
    {{user_obj.bio}}
  </div>
  <div class="row align-items">
    {% for post in user_obj.posts.all %}
    <div class="card mr-3 mb-3" style="width: 250px; overflow: hidden">
      {% if post.image %}
      <img
        src="{{post.image}}"
        class="card-img-top mb-2"
        alt="이미지를 찾을 수 없습니다."
        style="height: 150px; background-size: cover"
      />
      {% else %}
      <img
        src="media/posts/no-image.png"
        class="card-img-top mb-2"
        alt="이미지를 찾을 수 없습니다."
        style="height: 150px; background-size: cover"
      />
      {% endif %}
      <p class="text-right font-weight-lighter mb-0" style="font-size: 13px">
        {{post.created_at}}
      </p>
      <div class="card-body mt-1 pt-1">
        <h6 class="font-weight-bold" style="height: 50px">{{post.title}}</h6>
        <p class="card-text" style="height: 100px; overflow: auto">
          {{post.content}}
        </p>
        <div class="d-flex flex-column justify-content-end">
          <a href="{% url 'post:detail' post.pk %}" class="btn btn-primary mt-2"
            >더보기</a
          >
          {% if post.user == request.user %}
          <a href="{% url 'post:edit' post.pk %}" class="btn btn-primary mt-2"
            >수정하기</a
          >
          <a href="{% url 'post:delete' post.pk %}" class="btn btn-danger mt-2"
            >삭제하기</a
          >
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/accounts/signup.html
{% extends 'layout.html' %}
{% load bootstrap4 %} 

{% block title %} 
무제 | 회원가입 
{% endblock %} 

{% block content %}
<div class="container w-25">
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %} {% bootstrap_form form %} {% buttons %}
    <button type="submit" class="btn btn-primary">
      {{ submit_label|default:"회원가입" }}
    </button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

templates/accounts/update_profile.html
{% extends 'layout.html' %} 
{% load bootstrap4 %} 

{% block title %} 
무제 | 프로필수정 
{% endblock %} 

{% block content %}
<div class="container">
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %} 
    {% bootstrap_form form %} 
    {% buttons %}
    <button type="submit" class="btn btn-primary">
      {{ submit_label|default:"변경완료" }}
    </button>
    {% endbuttons %}
  </form>
  <a class="btn btn-primary" href="{% url 'accounts:change_password' %}" role="button">비밀번호 변경</a>
</div>
{% endblock %}