accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"


urlpatterns = [
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("profile/<int:pk>/", views.ProfileView.as_view(), name="profile"),
    path("profile_update/", views.UpdateProfileView.as_view(), name="profile_update"),
    path("change_password/", views.ChangePassword.as_view(), name="change_password"),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('wkdrmfmt/', admin.site.urls),
    path('', include('post.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views


app_name = "post"


urlpatterns = [
    path("", views.posts, name="home"),
    path("write/", views.CreatePosts.as_view(), name="write"),
    path("politics/", views.posts_politics, name="politics"),
    path("economy/", views.posts_economy, name="economy"),
    path("it/", views.posts_it, name="it"),
    path("company/", views.posts_company, name="company"),
    path("science/", views.posts_science, name="science"),
    path("society/", views.posts_society, name="society"),
    path("book_review/", views.posts_bookreview, name="book_review"),
    path("<int:pk>/", views.PostDetail.as_view(), name="detail"),
    path("edit/<int:pk>/", views.post_edit, name="edit"),
    path("delete/<int:pk>", views.post_delete, name="delete"),
    path("search/", views.SearchView.as_view(), name="search"),
]

post/models.py
from django.conf import settings
from django.db import models


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Post(BaseModel):
    class CountryChoice(models.TextChoices):
        KOREA = "K", "국내"
        WORLD = "W", "해외"

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="posts", on_delete=models.CASCADE
    )
    title = models.CharField(max_length=100)
    image = models.TextField(blank=True)
    content = models.TextField()
    content_img = models.ImageField(upload_to="posts/%Y/%m/%d", blank=True, null=True)
    comment = models.TextField(blank=True, null=True)
    post_url = models.URLField()
    country = models.CharField(max_length=2, choices=CountryChoice.choices)
    category = models.ManyToManyField("Category")
    like_user_set = models.ManyToManyField(
        settings.AUTH_USER_MODEL, blank=True, related_name="like_user_set"
    )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-id"]
        verbose_name_plural = "Post"


class Category(BaseModel):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Category"

post/forms.py
from django import forms
from . import models


class PostForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = [
            "post_url",
            "content",
            "content_img",
            "comment",
            "country",
            "category",
        ]
        widgets = {
            "post_url": forms.URLInput(),
            "category": forms.CheckboxSelectMultiple(),
        }


class CreatePostsForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = [
            "post_url",
            "content",
            "content_img",
            "comment",
            "country",
            "category",
        ]
        widgets = {
            "post_url": forms.URLInput(),
            "category": forms.CheckboxSelectMultiple(),
        }
        labels = {
            "post_url": "링크",
            "content": "내용",
            "content_img": "이미지 첨부",
            "comment": "코멘트",
            "country": "국가",
            "category": "카테고리",
        }
        help_texts = {
            "post_url": "'뉴스'링크만 입력해주세요.",
            "content": "기사내용을 요약해주세요.",
        }

    def save(self, *args, **kwargs):
        post = super().save(commit=False)
        return post


class SearchForm(forms.Form):
    search_content = forms.CharField()

post/views.py
import math
import requests
from accounts import mixins
from bs4 import BeautifulSoup
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http.response import Http404
from django.views.generic import DetailView, FormView, View
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from . import forms, models


def title_crawling(url):
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)AppleWebKit/537.36 (KHTML, like Gecko) Chrom e/73.0.3683.86 Safari/537.36"
    }
    data = requests.get(url, headers=headers)
    soup = BeautifulSoup(data.text, "html.parser")
    if soup.find("meta", {"property": "og:title"}):
        title = soup.find("meta", {"property": "og:title"}).get("content")
        img = soup.find("meta", {"property": "og:image"}).get("content")
    else:
        title = "제목이 없습니다."
        img = "이미지를 찾을 수 없습니다."
    return title, img


def img_download(url):
    r = requests.get(url)
    file = open("{{post.title}}.jpg", "wb")
    file.write(r.content)
    file.close()


def posts(request):
    post_list = models.Post.objects.all()
    paginator = Paginator(post_list, 12)
    page_number = request.GET.get("page", 1)
    post_list = paginator.get_page(page_number)
    count = 5
    end_page = paginator.count / 5

    if int(page_number) % count == 0:
        start = (int(int(page_number) / count) * count + 1) - count
        end = int(page_number)
    elif page_number == end_page:
        start = (int(int(page_number) / count) * count) + 1
        end = int(end_page)
    else:
        start = int(int(page_number) / count) * count
        end = (math.ceil(int(page_number) / count) * count) - 1

    print(type(start), type(end))
    page_obj = paginator.page_range[start:end]
    return render(
        request, "post/home.html", {"post_list": post_list, "page_obj": page_obj}
    )


def posts_politics(request):
    post_list = models.Post.objects.filter(category__name="정치")
    return render(request, "post/home.html", {"post_list": post_list})


def posts_economy(request):
    post_list = models.Post.objects.filter(category__name="경제")
    return render(request, "post/home.html", {"post_list": post_list})


def posts_it(request):
    post_list = models.Post.objects.filter(category__name="IT")
    return render(request, "post/home.html", {"post_list": post_list})


def posts_company(request):
    post_list = models.Post.objects.filter(category__name="기업")
    return render(request, "post/home.html", {"post_list": post_list})


def posts_science(request):
    post_list = models.Post.objects.filter(category__name="과학")
    return render(request, "post/home.html", {"post_list": post_list})


def posts_society(request):
    post_list = models.Post.objects.filter(category__name="사회/문화")
    return render(request, "post/home.html", {"post_list": post_list})


def posts_bookreview(request):
    post_list = models.Post.objects.filter(category__name="책 리뷰")
    return render(request, "post/home.html", {"post_list": post_list})


class CreatePosts(mixins.LoggedInOnlyView, FormView):

    form_class = forms.CreatePostsForm
    template_name = "post/write.html"

    def form_valid(self, form):
        post = form.save()
        post.user = self.request.user
        url = form.cleaned_data.get("post_url")
        post.title = title_crawling(url)[0]
        post.image = title_crawling(url)[1]
        post.save()
        form.save_m2m()
        messages.success(self.request, "작성 완료!")
        return redirect(reverse("post:detail", kwargs={"pk": post.pk}))


# @login_required
# def post_write(request):
#     if request.method == "POST":
#         form = forms.PostForm(request.POST, request.FILES)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.user = request.user
#             url = form.cleaned_data.get("post_url")
#             post.title = title_crawling(url)[0]
#             post.save()
#             form.save_m2m()
#             return redirect("post:home")
#     else:
#         form = forms.PostForm()

#     return render(request, "post/post_write.html", {'forms':form})


class PostDetail(DetailView):
    model = models.Post
    template_name = "post/detail.html"
    context_object_name = "forms"


@login_required
def post_edit(request, pk):
    post = get_object_or_404(models.Post, pk=pk)
    if request.method == "POST":
        form = forms.PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid:
            post = form.save(commit=False)
            if post.user == request.user:
                url = form.cleaned_data.get("post_url")
                post.title = title_crawling(url)[0]
                post.save()
                form.save_m2m()
                return redirect("post:detail", pk=pk)
            else:
                raise Http404
    else:
        if post.user == request.user:
            form = forms.PostForm(instance=post)
        else:
            raise Http404

    return render(request, "post/edit.html", {"forms": form})


@login_required
def post_delete(request, pk):
    post = get_object_or_404(models.Post, pk=pk)
    if post.user == request.user:
        post.delete()
        return redirect("post:home")
    else:
        Http404


class SearchView(View):
    def get(self, request):
        form = forms.SearchForm(request.GET)
        print(form)
        if form.is_valid():
            search = form.cleaned_data.get("search_content")
            title_post = models.Post.objects.filter(Q (title__icontains=search) | Q (content__icontains=search))
            return render(request, "post/search.html", {"form":form, "post_list":title_post})

        return render(request, "post/search.html", {"form":form})
    

def error(request):
    return render(request, "post/error.html")

templates/post/detail.html
{% extends 'layout.html' %}
{% load bootstrap4 %}

{% block content %}
<div class="container">
    <div class="card">
      <div class="card-header d-flex justify-content-between">
        <div class="font-weight-bold">
            {{forms.title}}
        </div>
        <div>
            {{forms.user.nickname}}   
        </div>   
      </div>
      <div class="card-body">
        <blockquote class="blockquote mb-0">
            {% if forms.image %}
                <img src="{{forms.image}}" class="card-img-top mb-2" alt="이미지를 찾을 수 없습니다.">
            {% else %}
            {% endif %}
             <p>
                {% if forms.content_img %}
                    <img src={{forms.content_img.url}}>
                {% endif %}
                 <p>
                     Content
            </p>
                <p style="font-size:16px;">{{forms.content}}</p>
            </p>
          <p class="font-italic font-weight-lighter" style="font-size:16px;">Comment</p>
          <p class="font-italic font-weight-lighter" style="font-size:16px;">{{forms.comment}}</p>
          <p class="font-italic font-weight-lighter text-right" style="font-size:16px;">{{forms.created_at}}</p>
        {% if forms.user == request.user %}
              <a href="{% url 'post:edit' forms.pk %}" class="btn btn-primary mt-2">수정하기</a>
              <a href="{% url 'post:delete' forms.pk %}" class="btn btn-danger mt-2">삭제하기</a>
         {% endif %}
        </blockquote>
      </div>
    </div>
</div>
{% endblock %}

templates/post/edit.html
{% extends 'layout.html' %} 
{% load bootstrap4 %} 

{% block content %}
<div class="container">
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %} {% bootstrap_form forms %} {% buttons %}
    <button type="submit" class="btn btn-primary">
      {{ submit_label|default:"Submit" }}
    </button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

templates/post/home.html
{% extends 'layout.html' %} 
{% block title %} 
  무제 
{% endblock %} 
{% block content %}
{% if messages %}
    <ul class="absolute top-0 mx-auto left-0 right-0 flex justify-center">
        {% for message in messages %}
            <li class="message font-medium bg-gray-700 z-10 rounded-full text-white py-4 px-6 w-3/12 text-center {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<div class="container" id="no-mobile-article">
  <div class="row align-items">
    {% for post in post_list %}
    <div class="card mr-3 mb-3 shadow-lg" style="height: 450px; width: 250px">
      {% if post.image %}
      <img
        src="{{post.image}}"
        class="card-img-top mb-2"
        alt="이미지를 찾을 수 없습니다."
        style="height: 150px; background-size: cover"
      />
      {% else %}
      <img
        src="media/posts/no-image.png"
        class="card-img-top mb-2"
        alt="이미지를 찾을 수 없습니다."
        style="height: 150px; background-size: cover"
      />
      {% endif %}
      <p class="text-right font-weight-lighter mb-0" style="font-size: 13px">
        {{post.created_at}}
      </p>
      <div class="card-body mt-1 pt-1">
        <h6 class="font-weight-bold" style="height: 50px">{{post.title}}</h6>
        <p class="card-text" style="height: 100px; overflow: auto">
          {{post.content}}
        </p>
        <div class="d-flex flex-column justify-content-end">
          <a href="{% url 'post:detail' post.pk %}" class="btn btn-primary"
            >더보기</a
          >
          <div
            class="text-right font-weight-light mt-3"
            style="font-size: 14px"
          >
            <a href="{% url 'accounts:profile' post.user.pk%}">
              작성자 : {{post.user.nickname}}
            </a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
    <div class="d-flex justify-content-center w-100">
      {% include 'partials/page_nav.html' %}
    </div>
  </div>
</div>



<div class="container" id="mobile-article">
  {% for post in post_list %}
  <div id="mobile-article" class="card mb-3" style="height: 100px;">
    <div class="d-flex flex-row">
      {% if post.image %}
      <div class="col-4" style="overflow: hidden; padding: 0;">
        <img src="{{post.image}}" alt="..." style="width: 100%; object-fit: cover;">
      </div>
      {% endif %}
      <div class="col-8" style="padding: 0;">
        <div class="card-body" style="font-size: 10px; padding: 4px; overflow: hidden;">
          <h5 class="card-title" style="font-size: 10px; margin-bottom: 8px; overflow: auto;">{{post.title}}</h5>
          <p class="card-text" style="font-size: 10px; height: 50px; margin-bottom: 8px; overflow: auto;">{{post.content}}</p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

templates/post/search.html
{% extends 'layout.html' %} 
{% block title %} 
검색결과
{% endblock %} 

{% block content %}
<div class="container">
    <div style="display:flex; justify-content: flex-end; margin-bottom: 20px;">
      <form class="form-inline" method="GET" action="{% url 'post:search' %}">
        <div class="form-group mx-sm-3 mb-2">
          <label for="inputPassword2" class="sr-only"></label>
          <input type="text" class="form-control" id="inputPassword2" placeholder="" name="search_content"/>
        </div>
        <button type="submit" class="btn btn-primary mb-2">검색</button>
      </form>
      {{form.value}}
    </div>
    <div class="row align-items">
      {% for post in post_list %}
      <div class="card mr-3 mb-3 shadow-lg" style="height: 450px; width: 250px">
        {% if post.image %}
        <img
          src="{{post.image}}"
          class="card-img-top mb-2"
          alt="이미지를 찾을 수 없습니다."
          style="height: 150px; background-size: cover"
        />
        {% else %}
        <img
          src="media/posts/no-image.png"
          class="card-img-top mb-2"
          alt="이미지를 찾을 수 없습니다."
          style="height: 150px; background-size: cover"
        />
        {% endif %}
        <p class="text-right font-weight-lighter mb-0" style="font-size: 13px">
          {{post.created_at}}
        </p>
        <div class="card-body mt-1 pt-1">
          <h6 class="font-weight-bold" style="height: 50px">{{post.title}}</h6>
          <p class="card-text" style="height: 100px; overflow: auto">
            {{post.content}}
          </p>
          <div class="d-flex flex-column justify-content-end">
            <a href="{% url 'post:detail' post.pk %}" class="btn btn-primary"
              >더보기</a
            >
            <div
              class="text-right font-weight-light mt-3"
              style="font-size: 14px"
            >
              <a href="{% url 'accounts:profile' post.user.pk%}">
                작성자 : {{post.user.nickname}}
              </a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
      <div class="d-flex justify-content-center w-100">
        {% include 'partials/page_nav.html' %}
      </div>
    </div>
  </div>
{% endblock %}

templates/post/write.html
{% extends 'layout.html' %}
{% load bootstrap4 %}

{% block content %}
<div class="container">
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %} {% bootstrap_form form %} {% buttons %}
    <button type="submit" class="btn btn-primary">
      {{ submit_label|default:"작성 완료" }}
    </button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}